name: Release Package to APT Repository

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build:
    name: Build Doovit Image & Push to S3
    runs-on: ubuntu-22.04-arm64-16c
    if: github.ref == 'refs/heads/arm64'
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ vars.AWS_DEFAULT_REGION }}
          role-to-assume: ${{ vars.AWS_DOOVIT_IMAGE_ROLE_ARN }}

      - uses: actions/checkout@v4
      - name: Build Image
        run: |
          export BASE_DIR=${GITHUB_WORKSPACE}
          sudo ./build-docker.sh -c ${GITHUB_WORKSPACE}/config.default

      - name: Publish Image to S3
        run: |
          aws s3 cp ${GITHUB_WORKSPACE}/deploy/*-arm64.img.xz s3://doovit-images/
          aws s3 cp ${GITHUB_WORKSPACE}/deploy/*-arm64-lite.img.xz s3://doovit-images/